
# -*- coding: utf-8 -*-
"""PINN_ODE_PDE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXFVBwqfDNbrVU2neVRPxX7hUeh55Scy

**ODE: dy/dx=cos(x)**
"""

import torch
import torch.nn as nn
import torch.autograd as autograd

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Define a simple feed-forward network
class PINN(nn.Module):
    def __init__(self, layers):
        super(PINN, self).__init__()
        self.linears = nn.ModuleList([nn.Linear(layers[i], layers[i+1])
                                      for i in range(len(layers)-1)])
        self.activation = nn.Tanh()

        # Xavier initialization
        for lin in self.linears:
            nn.init.xavier_normal_(lin.weight.data, gain=1.0)
            nn.init.zeros_(lin.bias.data)

    def forward(self, x):
        a = x
        for i in range(len(self.linears)-1):
            a = self.activation(self.linears[i](a))
        a = self.linears[-1](a)
        return a

# Example: Solve dy/dx = cos(x), y(0) = 0  (so true solution y = sin(x))
def residual(model, x):
    x = x.clone().requires_grad_(True).to(device)
    y = model(x)
    dy_dx = autograd.grad(y, x, torch.ones_like(y), create_graph=True)[0]
    return dy_dx - torch.cos(x)

# Boundary condition loss
def bc_loss(model, x0, y0):
    x0 = x0.to(device)
    y0 = y0.to(device)
    pred = model(x0)
    return torch.mean((pred - y0)**2)

# Training setup
model = PINN(layers=[1, 50, 50, 50, 1]).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
epochs = 15000

# Sample points in domain for residual
x_collocation = torch.linspace(0, 2*torch.pi, 100).view(-1,1)

# Boundary point
x0 = torch.tensor([[0.0]])
y0 = torch.tensor([[0.0]])

for epoch in range(epochs):
    optimizer.zero_grad()
    res = residual(model, x_collocation)
    loss_r = torch.mean(res**2)
    loss_bc = bc_loss(model, x0, y0)
    loss =loss_r + loss_bc
    loss.backward()
    optimizer.step()
    if epoch % 500 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.6f}")

import matplotlib.pyplot as plt
import numpy as np

# Test
x_test = torch.linspace(0, 2*torch.pi, 100).view(-1,1).to(device)
y_pred = model(x_test).detach().cpu().numpy()
import numpy as np
y_true = np.sin(x_test.cpu().numpy())
# === Compute error ===
mse = np.mean((y_pred - y_true)**2)
print(f"\nMean Squared Error (MSE): {mse:.8f}")

# === Plot ===
plt.figure(figsize=(8,5))
plt.plot(x_test.cpu(), y_true, label='True solution: sin(x)', linewidth=2)
plt.plot(x_test.cpu(), y_pred, '--', label='PINN prediction', linewidth=2)
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
#plt.title('PINN Approximation of dy/dx = cos(x), y(0)=0')
plt.grid(True)
filename = "PINN_sine.pdf"
plt.savefig(filename, format='pdf', bbox_inches='tight')
plt.show()

"""**Changing penalty term for physics loss**"""

import torch, torch.nn as nn, torch.autograd as autograd
import matplotlib.pyplot as plt
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# === Define network ===
class PINN(nn.Module):
    def __init__(self, layers):
        super(PINN, self).__init__()
        self.linears = nn.ModuleList(
            [nn.Linear(layers[i], layers[i+1]) for i in range(len(layers)-1)]
        )
        self.activation = nn.Tanh()
        for lin in self.linears:
            nn.init.xavier_normal_(lin.weight)
            nn.init.zeros_(lin.bias)

    def forward(self, x):
        a = x
        for i in range(len(self.linears)-1):
            a = self.activation(self.linears[i](a))
        return self.linears[-1](a)

# === ODE residual ===
def residual(model, x):
    x = x.clone().requires_grad_(True).to(device)
    y = model(x)
    dy_dx = autograd.grad(y, x, torch.ones_like(y), create_graph=True)[0]
    return dy_dx - torch.cos(x)

# === Boundary condition loss ===
def bc_loss(model, x0, y0):
    return torch.mean((model(x0.to(device)) - y0.to(device))**2)

# === Training function ===
def train_model(lambda_phys, epochs=15000):
    model = PINN([1, 50, 50, 50, 1]).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)
    x_col = torch.linspace(0, 2*np.pi, 100).view(-1,1)
    x0, y0 = torch.tensor([[0.0]]), torch.tensor([[0.0]])

    for epoch in range(epochs):
        opt.zero_grad()
        res = residual(model, x_col)
        loss_r = torch.mean(res**2)
        loss_bc = bc_loss(model, x0, y0)
        loss = lambda_phys*loss_r + loss_bc
        loss.backward()
        opt.step()
    return model

# === Train models for different penalty weights ===
lambdas = [0.1, 1, 100]
models = [train_model(l, epochs=15000) for l in lambdas]

# === Evaluate ===
x_test = torch.linspace(0, 2*np.pi, 200).view(-1,1).to(device)
y_true = np.sin(x_test.cpu().numpy())

plt.figure(figsize=(8,5))
plt.plot(x_test.cpu(), y_true, 'k', label='True sin(x)', linewidth=2)

# === Compute and print MSE for each model ===
for i, l in enumerate(lambdas):
    y_pred = models[i](x_test).detach().cpu().numpy()
    mse = np.mean((y_pred - y_true)**2)
    print(f"Î»_phys = {l:<5} â†’ MSE = {mse:.8f}")
    plt.plot(x_test.cpu(), y_pred, '--', label=f'Î»_phys = {l}')

plt.xlabel('x'); plt.ylabel('y')
#plt.title('Effect of Physics Loss Penalty (Î»_phys)')
plt.legend(); plt.grid(True)
filename = "PINN_sine_lam.pdf"
plt.savefig(filename, format='pdf', bbox_inches='tight')
plt.show()

"""# **PDE: 2-D heat equation (with different lamda)**


"""

import torch
import torch.nn as nn
import torch.autograd as autograd
import matplotlib.pyplot as plt
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- Neural network ---
class PINN(nn.Module):
    def __init__(self, layers):
        super(PINN, self).__init__()
        self.linears = nn.ModuleList(
            [nn.Linear(layers[i], layers[i+1]) for i in range(len(layers)-1)]
        )
        self.activation = nn.Tanh()
        for lin in self.linears:
            nn.init.xavier_normal_(lin.weight)
            nn.init.zeros_(lin.bias)

    def forward(self, x, t):
        X = torch.cat((x, t), dim=1)
        a = X
        for i in range(len(self.linears)-1):
            a = self.activation(self.linears[i](a))
        return self.linears[-1](a)

# --- PDE residual: u_t - Î± u_xx = 0 ---
def physics_residual(model, x, t, alpha=1.0):
    x.requires_grad = True
    t.requires_grad = True
    u = model(x, t)
    u_t = autograd.grad(u, t, torch.ones_like(u), create_graph=True)[0]
    u_x = autograd.grad(u, x, torch.ones_like(u), create_graph=True)[0]
    u_xx = autograd.grad(u_x, x, torch.ones_like(u_x), create_graph=True)[0]
    return u_t - alpha * u_xx

# --- Initial and boundary conditions ---
def initial_condition(x):
    return torch.sin(np.pi * x)

def train_model(lambda_phys=1.0, epochs=3000):
    model = PINN([2, 50, 50, 50, 1]).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    # Collocation points (physics)
    N_f = 2000
    x_f = torch.rand((N_f,1))
    t_f = torch.rand((N_f,1))

    # Boundary points
    N_b = 100
    x0 = torch.zeros((N_b,1))
    x1 = torch.ones((N_b,1))
    t_b = torch.rand((N_b,1))

    # Initial condition points
    N_i = 100
    x_i = torch.linspace(0,1,N_i).view(-1,1)
    t_i = torch.zeros((N_i,1))
    u_i = initial_condition(x_i)

    for epoch in range(epochs):
        optimizer.zero_grad()

        # Physics loss
        f = physics_residual(model, x_f.to(device), t_f.to(device))
        loss_f = torch.mean(f**2)

        # Boundary losses
        u_b0 = model(x0.to(device), t_b.to(device))
        u_b1 = model(x1.to(device), t_b.to(device))
        loss_b = torch.mean(u_b0**2) + torch.mean(u_b1**2)

        # Initial loss
        u_pred_i = model(x_i.to(device), t_i.to(device))
        loss_i = torch.mean((u_pred_i - u_i.to(device))**2)

        # Total loss
        loss = lambda_phys*loss_f + loss_b + loss_i
        loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Î»_phys={lambda_phys}, Loss={loss.item():.6f}")

    return model

# --- Prediction function ---
def predict(model, x, t):
    with torch.no_grad():
        u_pred = model(x.to(device), t.to(device)).cpu().numpy()
    return u_pred

# --- Setup grid for evaluation ---
x = torch.linspace(0,1,100).view(-1,1)
t = torch.linspace(0,1,100).view(-1,1)
X, T = torch.meshgrid(x.squeeze(), t.squeeze(), indexing='ij')
x_flat = X.reshape(-1,1)
t_flat = T.reshape(-1,1)

# Analytical true solution
u_true = np.exp(-np.pi**2 * 1.0 * T.numpy()) * np.sin(np.pi * X.numpy())

# --- Train for different Î»_phys ---
lambdas = [0.1, 1, 10, 100]
mse_values = []
models = []

for lam in lambdas:
    print(f"\nTraining with Î»_phys = {lam}")
    model = train_model(lambda_phys=lam, epochs=3000)
    models.append(model)

    # Predict
    u_pred = predict(model, x_flat, t_flat).reshape(100,100)
    mse = np.mean((u_pred - u_true)**2)
    mse_values.append(mse)
    print(f"Final MSE for Î»_phys={lam}: {mse:.6e}")

# --- Plot MSE vs Î»_phys ---
plt.figure(figsize=(6,4))
plt.plot(lambdas, mse_values, marker='o')
plt.xscale('log')
plt.xlabel('Î»_phys (log scale)')
plt.ylabel('Mean Squared Error (MSE)')
#plt.title('Effect of Physics Penalty on Accuracy')
plt.grid(True)
plt.savefig('heat_lamda.pdf', format='pdf', bbox_inches='tight')
plt.show()

# --- Visualization of best & worst models ---
best_idx = np.argmin(mse_values)
worst_idx = np.argmax(mse_values)
u_best = predict(models[best_idx], x_flat, t_flat).reshape(100,100)
u_worst = predict(models[worst_idx], x_flat, t_flat).reshape(100,100)

fig, axs = plt.subplots(1,3,figsize=(15,4))
im0 = axs[0].imshow(u_true, extent=[0,1,0,1], origin='lower', aspect='auto')
axs[0].set_title("True Solution")
im1 = axs[1].imshow(u_best, extent=[0,1,0,1], origin='lower', aspect='auto')
axs[1].set_title(f"Best Î»_phys={lambdas[best_idx]}, MSE={mse_values[best_idx]:.2e}")
im2 = axs[2].imshow(u_worst, extent=[0,1,0,1], origin='lower', aspect='auto')
axs[2].set_title(f"Worst Î»_phys={lambdas[worst_idx]}, MSE={mse_values[worst_idx]:.2e}")
for ax in axs: ax.set_xlabel('x'); ax.set_ylabel('t')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from google.colab import files

# --- Visualization of best & worst models ---
best_idx = np.argmin(mse_values)
worst_idx = np.argmax(mse_values)
u_best = predict(models[best_idx], x_flat, t_flat).reshape(100,100)
u_worst = predict(models[worst_idx], x_flat, t_flat).reshape(100,100)

fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# extent=[x_min, x_max, t_min, t_max]
# This puts x on the horizontal axis and t on the vertical axis
ext = [0, 1, 0, 1]

# Plot 0: True
axs[0].imshow(u_true, extent=ext, origin='lower', aspect='auto')
axs[0].set_title("True Solution",fontsize=16)
axs[0].text(0.5, -0.4, "(a)", transform=axs[0].transAxes, size=15, ha="center",weight='bold')

# Plot 1: Best
axs[1].imshow(u_best, extent=ext, origin='lower', aspect='auto')
axs[1].set_title(f"Best Î»_phys={lambdas[best_idx]}, MSE={mse_values[best_idx]:.2e}",fontsize=16)
axs[1].text(0.5, -0.4, "(b)", transform=axs[1].transAxes, size=15, ha="center",weight='bold')

# Plot 2: Worst
axs[2].imshow(u_worst, extent=ext, origin='lower', aspect='auto')
axs[2].set_title(f"Worst Î»_phys={lambdas[worst_idx]}, MSE={mse_values[worst_idx]:.2e}",fontsize=16)
axs[2].text(0.5, -0.4, "(c)", transform=axs[2].transAxes, size=15, ha="center",weight='bold')

# Axis labels swapped as requested
for ax in axs:
    ax.set_xlabel('x',fontsize=16)
    ax.set_ylabel('t',fontsize=16)

    # This specifically targets the numbers (values) on the axes
    ax.tick_params(axis='both', which='major', labelsize=16)
    ax.tick_params(axis='both', which='minor', labelsize=16)

plt.tight_layout()

# Save as PDF for high accuracy in your paper
filename = "model_comparison_xt.pdf"
plt.savefig(filename, format='pdf', bbox_inches='tight')
plt.show()

# Trigger download
files.download(filename)
